version: 2.1
orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            tags:
              only: /^v.*/
